service: affiliate-marketing-automation

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  deploymentBucket:
    name: automation-affiliate-marketing
  stackTags:
    Project: "AffiliateMarketingAutomation"
    DeployedBy: "GitHub"
  timeout: 30

package:
  exclude:
    - .gitignore
    - .github/**
    - README.md
  excludeDevDependencies: true

functions:
  hello:
    handler: lambda_function.execute
    events:
      - http:
          path: /
          method: get
          cors: true

plugins:
  - serverless-python-requirements